export enum ETypeOrmAwsConnectorRotationDeferredReason {
	DATA_SOURCE_NOT_INITIALIZED = "DATA_SOURCE_NOT_INITIALIZED",
	RETIRING_GENERATION_ACTIVE = "RETIRING_GENERATION_ACTIVE",
	RETIRING_GENERATION_CLOSE_FAILED = "RETIRING_GENERATION_CLOSE_FAILED",
	ROTATION_IN_PROGRESS = "ROTATION_IN_PROGRESS",
	SHUTDOWN_IN_PROGRESS = "SHUTDOWN_IN_PROGRESS",
}
